services:
  cockroach:
    image: cockroachdb/cockroach:v24.1.0
    container_name: cockroachdb
    command: start-single-node --insecure
    ports:
      - "26357:26257"   # SQL (external:internal)
      - "8081:8080"     # Admin UI
    volumes:
      - cockroach-data:/cockroach/cockroach-data

volumes:
  cockroach-data:
